spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankRest-main
    username: admin
    password: bank
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bankcards-group
      auto-offset-reset: earliest

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs